force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Finished__c.field-meta.xml
<CustomField>
    <fullName>Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/RecordID__c.field-meta.xml
<CustomField>
    <fullName>RecordID__c</fullName>
    <label>RecordID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CheckListController.cls
public with sharing class CheckListController {
    @AuraEnabled
    public static List<Checklist__c> getRecords(string recordid) {
        List<vincere__Checklist__c> checklist =
                [SELECT Id, RecordID__c, Name,Finished__c, Description__c FROM Checklist__c WHERE RecordID__c LIKE :recordid ORDER BY id ASC];
        return checklist;
    }
    @AuraEnabled
    public static void addRecord(string recordid) {
        Checklist__c  ChecklistTask = new Checklist__c(RecordID__c = recordid);
        ChecklistTask.Name = null;
        insert ChecklistTask;
    }
    @AuraEnabled
    public static void updateRecord(Checklist__c ChecklistRecord) {
        system.debug(ChecklistRecord);
        update ChecklistRecord;
    }
    @AuraEnabled
    public static void deleteRecord(Checklist__c ChecklistRecord) {
        delete ChecklistRecord;
    }
}